### PR TITLE
Port dentOS patches from Linux 5.10

### PR DESCRIPTION
**Pull request by taraschornyiplv**
Update prestera driver to v3.2.1

### CODE REVIEW

**Review by paulmenzel — COMMENTED** [review]
> Port dentOS patches form Linux 5.10

s/form/from/

Please also mention to where, and please write some description, from what branch it was taken, what porting problems there were, and so on.

[Fix bridge userspace stp state](https://github.com/dentproject/linux/pull/3/commits/c85ecb5dee8e961090456e2eea21021e0f31f8ae) misses a prefix, a description of the problem, and how it’s fixed.

Same for the last commit updating the version.

**Review by eladnachman — APPROVED** [review]

**Review by Mickey201 — APPROVED** [review]

**Review by robimarko — APPROVED** [review]

**Comment by taraschornyiplv** [comment]
> > Port dentOS patches form Linux 5.10
> 
> s/form/from/
> 
> Please also mention to where, and please write some description, from what branch it was taken, what porting problems there were, and so on.
> 
> [Fix bridge userspace stp state](https://github.com/dentproject/linux/pull/3/commits/c85ecb5dee8e961090456e2eea21021e0f31f8ae) misses a prefix, a description of the problem, and how it’s fixed.
> 
> Same for the last commit updating the version.

W/o STP path there is an issue with port STP state when using userspace STP(mstpd). When a port is in blocked stare and user will disable STP via brctl and remove bridge port will remain in blocking state indefinately

**Comment by paulmenzel** [comment]
Please amend the corresponding commit message.

**Comment by snobleaws** [comment]
LMK when we feel we have the right patches + commit comments to get this merged.

**Comment by eladnachman** [comment]
We feel we have the right patches and have explained the commit comments, plus this have passed testing in Marvell. As far as we are concerned, this can be merged.

**Comment by paulmenzel** [comment]
For example, commit https://github.com/dentproject/linux/pull/3/commits/c85ecb5dee8e961090456e2eea21021e0f31f8ae still lacks a proper commit message.

**Pull request merged**
