### PR TITLE
prestera_router: handle IPv4 routes with external nexthop

### LINKED ISSUE #232: Installing IPv4 routes setting nexthop via NHID fails and breaks routing with FRR (e.g. BGP)
Following the setup at https://docs.bisdn.de/network_configuration/bgp.html#bgp-for-ipv4-networks (with the addition of ` bgp ebgp-requires-policy` so the peers talk to each other) route information gets exchanged and distributed, but FRR fails to install any route on the switch:

```
Jul 19 11:19:20 localhost systemd[1]: Started FRRouting.
Jul 19 11:19:22 localhost bgpd[998]: [M59KS-A3ZXZ] bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.0.2 in vrf default
Jul 19 11:19:24 localhost zebra[986]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=16, pid=2180819141
Jul 19 11:19:24 localhost zebra[986]: [VYKYC-709DP] default(0:254):10.0.2.0/24: Route install failed
Jul 19 11:19:25 localhost zebra[986]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=19, pid=2180819141
Jul 19 11:19:25 localhost zebra[986]: [VYKYC-709DP] default(0:254):10.0.101.2/32: Route install failed
Jul 19 11:19:26 localhost bgpd[998]: [M59KS-A3ZXZ] bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.1.2 in vrf default
Jul 19 11:19:26 localhost zebra[986]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=22, pid=2180819141
Jul 19 11:19:26 localhost zebra[986]: [VYKYC-709DP] default(0:254):10.0.100.2/32: Route install failed
Jul 19 11:19:34 localhost zebra[986]: [WPPMZ-G9797] if_zebra_speed_update: swp5 old speed: 4294967295 new speed: 1000
Jul 19 11:19:35 localhost zebra[986]: [WPPMZ-G9797] if_zebra_speed_update: swp52 old speed: 4294967295 new speed: 10000
```

The consequence is that while routes are distributed, they don't actually work, as the learned routes are not installed in the routing table (and also not offloaded).

The same thing happens with other protocols (RIP, OSPF, ...), but does not happen for [BGP with IPv6](https://docs.bisdn.de/network_configuration/bgp.html#bgp-for-ipv6-networks).

Turning on debug for zebra, it shows the following:

```
Jul 19 11:35:10 localhost zebra[959]: [YXCJP-0WZWV] netlink_nexthop_msg_encode: ID (17): directly connected, swp5(8) vrf default(0)
Jul 19 11:35:10 localhost zebra[959]: [R43C6-KYHWT] netlink_nexthop_msg_encode: RTM_NEWNEXTHOP, id=17
Jul 19 11:35:10 localhost zebra[959]: [HYEHE-CQZ9G] nl_batch_send: netlink-dp (NS 0), batch size=40, msg cnt=1
Jul 19 11:35:10 localhost zebra[959]: [TJ327-ET8HE] netlink_send_msg: >> netlink message dump [sent]
Jul 19 11:35:10 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=40 type=(104) NEWNEXTHOP flags=(0x0501) {REQUEST,DUMP,(ROOT|REPLACE|CAPPED),(ATOMIC|CREATE)} seq=19 pid=2182728561]
Jul 19 11:35:10 localhost zebra[959]: [WCX94-SW894]   nhm [family=(2) AF_INET scope=(0) UNIVERSE protocol=(11) ZEBRA flags=0x00000000 {}]
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(1) ID]
Jul 19 11:35:10 localhost zebra[959]: [Z4E9C-GD9EP]       17
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(5) OIF]
Jul 19 11:35:10 localhost zebra[959]: [JR4EA-BKPTA]       8
Jul 19 11:35:10 localhost zebra[959]: [YXCJP-0WZWV] netlink_nexthop_msg_encode: ID (19): 10.0.0.2, via swp52(55) vrf default(0)
Jul 19 11:35:10 localhost zebra[959]: [R43C6-KYHWT] netlink_nexthop_msg_encode: RTM_NEWNEXTHOP, id=19
Jul 19 11:35:10 localhost zebra[959]: [HYEHE-CQZ9G] nl_batch_send: netlink-dp (NS 0), batch size=48, msg cnt=1
Jul 19 11:35:10 localhost zebra[959]: [TJ327-ET8HE] netlink_send_msg: >> netlink message dump [sent]
Jul 19 11:35:10 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=48 type=(104) NEWNEXTHOP flags=(0x0501) {REQUEST,DUMP,(ROOT|REPLACE|CAPPED),(ATOMIC|CREATE)} seq=21 pid=2182728561]
Jul 19 11:35:10 localhost zebra[959]: [WCX94-SW894]   nhm [family=(2) AF_INET scope=(0) UNIVERSE protocol=(11) ZEBRA flags=0x00000000 {}]
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(1) ID]
Jul 19 11:35:10 localhost zebra[959]: [Z4E9C-GD9EP]       19
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(6) GATEWAY]
Jul 19 11:35:10 localhost zebra[959]: [M8QV4-KY9C0]       10.0.0.2
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(5) OIF]
Jul 19 11:35:10 localhost zebra[959]: [JR4EA-BKPTA]       55
Jul 19 11:35:10 localhost zebra[959]: [YXPF5-B2CE0] netlink_route_multipath_msg_encode: RTM_NEWROUTE 10.0.2.0/24 vrf 0(254)
Jul 19 11:35:10 localhost zebra[959]: [J87BH-XW5PP] netlink_route_multipath_msg_encode: 10.0.2.0/24 nhg_id is 19
Jul 19 11:35:10 localhost zebra[959]: [HYEHE-CQZ9G] nl_batch_send: netlink-dp (NS 0), batch size=52, msg cnt=1
Jul 19 11:35:10 localhost zebra[959]: [TJ327-ET8HE] netlink_send_msg: >> netlink message dump [sent]
Jul 19 11:35:10 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=52 type=(24) NEWROUTE flags=(0x0501) {REQUEST,DUMP,(ROOT|REPLACE|CAPPED),(ATOMIC|CREATE)} seq=22 pid=2182728561]
Jul 19 11:35:10 localhost zebra[959]: [GCEGC-W8YBF]   rtmsg [family=(2) AF_INET dstlen=24 srclen=0 tos=0 table=254 protocol=(186) BGP scope=(0) UNIVERSE type=(1) UNICAST flags=0x0000 {}]
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(1) DST]
Jul 19 11:35:10 localhost zebra[959]: [M8QV4-KY9C0]       10.0.2.0
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(6) PRIORITY]
Jul 19 11:35:10 localhost zebra[959]: [Z4E9C-GD9EP]       20
Jul 19 11:35:10 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(30) NH_ID]
Jul 19 11:35:10 localhost zebra[959]: [Z4E9C-GD9EP]       19
Jul 19 11:35:10 localhost zebra[959]: [V8KNF-8EXH8] netlink_recv_msg: << netlink message dump [recv]
Jul 19 11:35:10 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=36 type=(2) ERROR flags=(0x0100) {DUMP,(ROOT|REPLACE|CAPPED)} seq=22 pid=2182728561]
Jul 19 11:35:10 localhost zebra[959]: [KWP1C-6CSXF]   nlmsgerr [error=(-22) Invalid argument]
Jul 19 11:35:10 localhost zebra[959]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=22, pid=2182728561
Jul 19 11:35:10 localhost zebra[959]: [QTT8V-3ZQ34] nl_batch_read_resp: netlink error message seq=22
Jul 19 11:35:10 localhost zebra[959]: [VYKYC-709DP] default(0:254):10.0.2.0/24: Route install failed
...
Jul 19 11:35:12 localhost zebra[959]: [YXCJP-0WZWV] netlink_nexthop_msg_encode: ID (24): 10.0.1.2, via swp5(8) vrf default(0)
Jul 19 11:35:12 localhost zebra[959]: [R43C6-KYHWT] netlink_nexthop_msg_encode: RTM_NEWNEXTHOP, id=24
Jul 19 11:35:12 localhost zebra[959]: [YXPF5-B2CE0] netlink_route_multipath_msg_encode: RTM_NEWROUTE 10.0.100.2/32 vrf 0(254)
Jul 19 11:35:12 localhost zebra[959]: [J87BH-XW5PP] netlink_route_multipath_msg_encode: 10.0.100.2/32 nhg_id is 24
Jul 19 11:35:12 localhost zebra[959]: [YXPF5-B2CE0] netlink_route_multipath_msg_encode: RTM_NEWROUTE 10.0.101.2/32 vrf 0(254)
Jul 19 11:35:12 localhost zebra[959]: [J87BH-XW5PP] netlink_route_multipath_msg_encode: 10.0.101.2/32 nhg_id is 19
Jul 19 11:35:12 localhost zebra[959]: [HYEHE-CQZ9G] nl_batch_send: netlink-dp (NS 0), batch size=152, msg cnt=3
Jul 19 11:35:12 localhost zebra[959]: [TJ327-ET8HE] netlink_send_msg: >> netlink message dump [sent]
Jul 19 11:35:12 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=48 type=(104) NEWNEXTHOP flags=(0x0501) {REQUEST,DUMP,(ROOT|REPLACE|CAPPED),(ATOMIC|CREATE)} seq=24 pid=2182728561]
Jul 19 11:35:12 localhost zebra[959]: [WCX94-SW894]   nhm [family=(2) AF_INET scope=(0) UNIVERSE protocol=(11) ZEBRA flags=0x00000000 {}]
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(1) ID]
Jul 19 11:35:12 localhost zebra[959]: [Z4E9C-GD9EP]       24
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(6) GATEWAY]
Jul 19 11:35:12 localhost zebra[959]: [M8QV4-KY9C0]       10.0.1.2
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(5) OIF]
Jul 19 11:35:12 localhost zebra[959]: [JR4EA-BKPTA]       8
Jul 19 11:35:12 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=52 type=(24) NEWROUTE flags=(0x0501) {REQUEST,DUMP,(ROOT|REPLACE|CAPPED),(ATOMIC|CREATE)} seq=25 pid=2182728561]
Jul 19 11:35:12 localhost zebra[959]: [GCEGC-W8YBF]   rtmsg [family=(2) AF_INET dstlen=32 srclen=0 tos=0 table=254 protocol=(186) BGP scope=(0) UNIVERSE type=(1) UNICAST flags=0x0000 {}]
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(1) DST]
Jul 19 11:35:12 localhost zebra[959]: [M8QV4-KY9C0]       10.0.100.2
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(6) PRIORITY]
Jul 19 11:35:12 localhost zebra[959]: [Z4E9C-GD9EP]       20
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(30) NH_ID]
Jul 19 11:35:12 localhost zebra[959]: [Z4E9C-GD9EP]       24
Jul 19 11:35:12 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=52 type=(24) NEWROUTE flags=(0x0501) {REQUEST,DUMP,(ROOT|REPLACE|CAPPED),(ATOMIC|CREATE)} seq=26 pid=2182728561]
Jul 19 11:35:12 localhost zebra[959]: [GCEGC-W8YBF]   rtmsg [family=(2) AF_INET dstlen=32 srclen=0 tos=0 table=254 protocol=(186) BGP scope=(0) UNIVERSE type=(1) UNICAST flags=0x0000 {}]
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(1) DST]
Jul 19 11:35:12 localhost zebra[959]: [M8QV4-KY9C0]       10.0.101.2
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(6) PRIORITY]
Jul 19 11:35:12 localhost zebra[959]: [Z4E9C-GD9EP]       20
Jul 19 11:35:12 localhost zebra[959]: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(30) NH_ID]
Jul 19 11:35:12 localhost zebra[959]: [Z4E9C-GD9EP]       19
Jul 19 11:35:12 localhost zebra[959]: [V8KNF-8EXH8] netlink_recv_msg: << netlink message dump [recv]
Jul 19 11:35:12 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=36 type=(2) ERROR flags=(0x0100) {DUMP,(ROOT|REPLACE|CAPPED)} seq=25 pid=2182728561]
Jul 19 11:35:12 localhost zebra[959]: [KWP1C-6CSXF]   nlmsgerr [error=(-22) Invalid argument]
Jul 19 11:35:12 localhost zebra[959]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=25, pid=2182728561
Jul 19 11:35:12 localhost zebra[959]: [QTT8V-3ZQ34] nl_batch_read_resp: netlink error message seq=25
Jul 19 11:35:12 localhost zebra[959]: [V8KNF-8EXH8] netlink_recv_msg: << netlink message dump [recv]
Jul 19 11:35:12 localhost zebra[959]: [JAS4D-NCWGP] nlmsghdr [len=36 type=(2) ERROR flags=(0x0100) {DUMP,(ROOT|REPLACE|CAPPED)} seq=26 pid=2182728561]
Jul 19 11:35:12 localhost zebra[959]: [KWP1C-6CSXF]   nlmsgerr [error=(-22) Invalid argument]
Jul 19 11:35:12 localhost zebra[959]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=26, pid=2182728561
Jul 19 11:35:12 localhost zebra[959]: [QTT8V-3ZQ34] nl_batch_read_resp: netlink error message seq=26
Jul 19 11:35:12 localhost zebra[959]: [VYKYC-709DP] default(0:254):10.0.100.2/32: Route install failed
Jul 19 11:35:12 localhost zebra[959]: [VYKYC-709DP] default(0:254):10.0.101.2/32: Route install failed
```

so the issue seems to be installing routes pointing to a previously created nexthop.

This is using DentOS main, on TN48M-DN.

minimal reproducer via ip commands:

```
ip link set up swp5
ip a a 10.0.0.1/24 dev swp5
ip nexthop add dev eno5 id 20 via 10.0.0.2
ip route add 10.0.1.0/24 nhid 20
RTNETLINK answers: Invalid argument
```

The above fails on DentOS, but e.g. succeeds in ubuntu.

### PR DESCRIPTION
**Pull request by KanjiMonster**
Properly handle IPv4 routes referencing a nexthop via its ID and do not reject these routes anymore.

When creating a route referencing a nexthop via its ID, the nexthop will be stored in a separate pointer instead of the array of nexthops in the fib_info struct. This causes issues since fib_info_nh() only handles the nexthops array, but not single nexthop pointer.

In contrast fib_info_nhc() handles both, but retuns a fib_nh_common pointer instead of a fib_nh pointer. Luckily we only ever fields from the fib_nh_common parts, so we can just replace all instances of fib_info_nh() with fib_info_nhc() and access the fields via their fib_nh_common names.

This allows handling IPv4 routes with an external nexthop, and we do not need to reject them anymore.

Fixes FRR failing to install learned IPv4 routes into the kernel:

    Jul 19 11:19:22 localhost bgpd[998]: [M59KS-A3ZXZ] bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.0.2 in vrf default
    Jul 19 11:19:24 localhost zebra[986]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=16, pid=2180819141
    Jul 19 11:19:24 localhost zebra[986]: [VYKYC-709DP] default(0:254):10.0.2.0/24: Route install failed
    Jul 19 11:19:25 localhost zebra[986]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=19, pid=2180819141
    Jul 19 11:19:25 localhost zebra[986]: [VYKYC-709DP] default(0:254):10.0.101.2/32: Route install failed
    Jul 19 11:19:26 localhost bgpd[998]: [M59KS-A3ZXZ] bgp_update_receive: rcvd End-of-RIB for IPv4 Unicast from 10.0.1.2 in vrf default
    Jul 19 11:19:26 localhost zebra[986]: [WVJCK-PPMGD][EC 4043309093] netlink-dp (NS 0) error: Invalid argument, type=RTM_NEWROUTE(24), seq=22, pid=2180819141
    Jul 19 11:19:26 localhost zebra[986]: [VYKYC-709DP] default(0:254):10.0.100.2/32: Route install failed

### CODE REVIEW

**Comment by KanjiMonster** [comment]
This fixes [dentOS/issues/232](https://github.com/dentproject/dentOS/issues/232).  Tested routing and (stateful) NAT, both still working.

**Comment by taraschornyiplv** [comment]
LGMT

**Review by taraschornyiplv — APPROVED** [review]

**Review by paulmenzel — APPROVED** [review]
Thank you for fixing this and the explanatory commit message. Great work.

**Review by eladnachman — APPROVED** [review]

**Review by sandnaga — APPROVED** [review]
Approved

**Pull request merged**
